{{ if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rancher-servicemonitor.fullname" . }}
  labels:
    {{- include "rancher-servicemonitor.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
  selector:
    matchLabels:
    {{- include "rancher-servicemonitor.selectorLabels" . | nindent 4 }}
{{ end }}
