# https://ko.build/configuration/

name: Publish
on:
  push:

jobs:
  publish:
    if: github.actor != 'depbot' 
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup ko
        uses: ko-build/setup-ko@v0.6
      - name: build ghcr
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          ko build --bare
          ko build --bare -t $VERSION
        env:
          KO_DEFAULTPLATFORMS: linux/arm64,linux/amd64
      - name: build mtr
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          ko login -u "${MTR_USERNAME}" -p "${MTR_PASSWORD}" ${MTR}
          ko build --bare
          ko build --bare -t $VERSION
        env:
          KO_DEFAULTPLATFORMS: linux/arm64,linux/amd64
          MTR_USERNAME: ${{secrets.MTR_USERNAME}}
          MTR_PASSWORD: ${{secrets.MTR_PASSWORD}}
          KO_DOCKER_REPO: mtr.devops.telekom.de/caas/rancher-servicemonitor
          MTR: mtr.devops.telekom.de
  dependbot:
    if: github.actor == 'depbot' 
    name: Buildtest
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup ko
        uses: ko-build/setup-ko@v0.6
      - name: build ghcr
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          ko build --bare
          ko build --bare -t $VERSION
        env:
          KO_DEFAULTPLATFORMS: linux/arm64,linux/amd64
          KO_DOCKER_REPO: ko.local
